name: Build library and run tests
on:
  push:
    branches: [ master, devel ]
    paths:
    - '.github/workflows/**'
    - 'include/**'
    - 'src/**'
    - 'tests/**'
    - 'CMakeLists.txt'
jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install gtest
        run: sudo apt-get install libgtest-dev
      - uses: actions/checkout@v3
      - name: Build & Test
        run: |
          cd build
          cmake ..
          make
          CTEST_OUTPUT_ON_FAILURE=TRUE make test
